git:
  depth: 3

language: c

os:
  - linux
  - osx

env:
  - OCAML_VERSION=4.06

sudo: required

install:
  - curl -O https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam update
  - opam install dune re

script:
  - make

notifications:
  email:
    on_success: never
    on_failure: change
